name: flutter_auth_app
description: A Flutter authentication app with .NET Web API backend
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  get: ^4.7.2
  fluttertoast: 8.2.8
  flutter_easyloading: 3.0.5
  flutter_svg: 2.0.10+1
  flutter_staggered_grid_view: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
